# Core
obj-$(CONFIG_PINCTRL_FTSCU010)	+= pinctrl-ftscu010.o

# SoC Drivers
obj-$(CONFIG_PINCTRL_A380)	+= pinctrl-a380.o
obj-$(CONFIG_PINCTRL_A500)	+= pinctrl-a500.o
obj-$(CONFIG_PINCTRL_GC1601)	+= pinctrl-gc1601.o
obj-$(CONFIG_PINCTRL_GC1610)	+= pinctrl-gc1610.o
obj-$(CONFIG_PINCTRL_LEO)	+= pinctrl-leo.o
obj-$(CONFIG_PINCTRL_TC12NGRC)	+= pinctrl-tc12ngrc.o
