
# Makefile for Faraday board clocks

obj-y	+= clk.o clk-pll.o

obj-$(CONFIG_MACH_A380)	+= clk-a380.o
obj-$(CONFIG_A500_PLATFORM)	+= clk-a500.o
obj-$(CONFIG_A600_PLATFORM)	+= clk-a600.o
obj-$(CONFIG_MACH_GC1601)	+= clk-gc1601.o
obj-$(CONFIG_GC1610_PLATFORM)	+= clk-gc1610.o
obj-$(CONFIG_MACH_LEO)	+= clk-leo.o
obj-$(CONFIG_MACH_TC12NGRC)	+= clk-tc12ngrc.o
