#
# Makefile for the Realtek network device drivers.
#

obj-$(CONFIG_8139CP) += 8139cp.o
obj-$(CONFIG_8139TOO) += 8139too.o
obj-$(CONFIG_ATP) += atp.o
obj-$(CONFIG_R8168) += r8168-8.046.00/src/r8168_asf.o r8168-8.046.00/src/r8168_n.o r8168-8.046.00/src/rtl_eeprom.o r8168-8.046.00/src/rtltool.o
obj-$(CONFIG_R8169) += r8169.o
