dtb-$(CONFIG_A500_PLATFORM) += a500.dtb
dtb-$(CONFIG_A600_PLATFORM) += a600.dtb a600_trustzone.dtb a600_haps.dtb
dtb-$(CONFIG_GC1610_PLATFORM) += gc1610.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
